### ISSUE TITLE
Ability to add pre and post processing of config

### ISSUE THREAD

**Issue by empi89** [netdevops/hier_config#73]
I am adding functionality for HPE Comware switches. However, as VLAN configuration mixes multiple vlans into the same configuration statement things are getting a bit complicated. I have written a pre/post processor for dealing with it. However from architectural standpoints this is a mess. 

Could you please advise on a more generic approach to implement it?

See my request for comments branch on this: https://github.com/empi89/hier_config/tree/rfc-pre-and-postprocessing

**Comment by aedwardstx** [comment]
In my environment, I solve these types of issues with post running and compiled config load fixups. These fixups happen before the running and compiled config comparison to build remediation conifg. See the below example. I'm open to these sorts of fixups being part of the project. 

running config
```
vlan 1-3,5
```
compiled config
```
vlan 1
  name ABCD
vlan 2,3,5
```
Would be normalized to the following in the running config:
```
vlan 1
vlan 2
vlan 3
vlan 5
```
And would be normalized to the following in the running config:
```
vlan 1
  name ABCD
vlan 2
vlan 3
vlan 5
```
Then, the resulting remediation config would reflect the appropriate changes:
```
vlan 1
  name ABCD
```

**Comment by empi89** [comment]
I have changed the branch a bit. Is this as you intended?

**Comment by v0tti** [comment]
I have similar issues with VLAN ranges. I think additionally to the Comware specific changes a generic approach would be helpful.

**Comment by itdependsnetworks** [comment]
This may be helpful to help manage vlan configurations https://netutils.readthedocs.io/en/latest/netutils/vlan/index.html

**Comment by aedwardstx** [comment]
Since the merge of https://github.com/netdevops/hier_config/pull/133, there are now clear examples on how to write post_load_callbacks to fixup a configuration https://github.com/netdevops/hier_config/blob/master/hier_config/platforms/cisco_ios/driver.py#L177.
